### ISSUE TITLE
Duplicate Planes

### ISSUE THREAD

**Issue by Dirk-tooth** [Dirk-tooth/magicJS#4]
Some planes are printed multiple times, need way include only latest printing.

**Comment by brokengekko** [comment]
`
var temp_object = [];
var found_planes = [];
$(master_data_object).each(function(){
	if (!found_planes.includes(this['name'])){
		found_planes.push(this['name']);
		temp_object.push(this);
	}
});
master_data_object = temp_object;
temp_object = [];
found_planes = [];`

**Comment by Dirk-tooth** [comment]
Thanks @brokengekko, I think I'll just add an extra variable to the request the filters by set and only get the anthology set (that should cover usn until they start printing more)

**Comment by Dirk-tooth** [comment]
Okay this is closed - I added a "set" variable to the request and now it only returns planes from PCA. Ive tested it and pushed it up to master.
